### ISSUE TITLE
Problem with OO interface in parallelized environment

### ISSUE THREAD

**Issue by danhar** [jacobwilliams/bspline-fortran#12]
This is similar to issue #4 but now I tried the OO module. When compiled with -openmp, my code builds but crashes with SIGSEGV at runtime. This does not happen without -openmp.

When I add the SAVE attribute to the spline instance, e.g.,
```fortran
type(bspline_2d) ,save:: v_spline
```
the program runs without crashing. Each thread gets its own copy by
```fortran
!$OMP PARALLEL PRIVATE(v_spline)
```
I am not quite sure why this is happening. Could it be that the default initialization in the derived type declaration, e.g.,
```fortran
integer :: inbvy = 1
integer :: iloy = 1
```
puts the variables on stack, thereby making them global (like the problem in #4 )? Or maybe my workaround with SAVE is erroneous? I could also imagine that this is a compiler bug, I tested with Intel composer_xe_2015.1.133 and composer_xe_2015.0.090, fairly recent compilers. Strangely enough, the problem also disappears if the compiler option -ftrapuv (which I use for debugging) is specified.

I have put substantial effort in moving my code to the OO version and in investigating this issue, and would be very grateful for any help.

**Comment by jacobwilliams** [comment]
I don't see why the variable initialization inside the type should interfere with OpenMP. Is it possible to post a complete reproducer that exhibits the problem? That would make it easier for me to help.

**Comment by jacobwilliams** [comment]
It's possible it could be because the type has allocatable components? See [this post](https://software.intel.com/en-us/forums/intel-fortran-compiler-for-linux-and-mac-os-x/topic/270067).

**Comment by szaghi** [comment]
>I don't see why the variable initialization inside the type should interfere with OpenMP

I do notead all the Intel-forum thread, but I feel that @jacobwilliams is right. OpenMP does not support all Fortran features, i.e. derived type with *complex* data structure is poorely supported.

As @jacobwilliams pointed out, I feel that probably the *thread copy* of `firstprivate` is not able to really create a copy of the `bspline_2d` type, it having allocatable arrays members. A minimal working example reproducing the error is very helpful to find the real reason, as well the info about the compiler (I had a lot of problem with Intel <= 11.x with OpenMP due to compiler's bugs then fixed).

In the case the problem is due to the failing thread-copy, I do not figure out why *save* workaround works. IMO, I could try with an explicit copy into the thread-parallel block using the derived-type assignement/TPB-copy.

My best regards.

**Comment by danhar** [comment]
Thanks for replying so quickly and pointing me in the right direction. Funnily enough, the post that @jacobwilliams pointed to is one that I contributed to, about 3.5 years ago... (though I was pretty confused, my problem there had nothing to do with the original post). Today I spent many hours researching and think I figured it out. Let me try to summarize. 

OpenMP doesn't support derived types with allocatable components, not even in its latest standard 4.0, which is a pity. Denote the derived type instance by dti. I had `!$OMP PRIVATE(dti)`, which made dti undefined. Here are some workarounds. 
1. Make dti local within the parallel environment, e.g., by moving the code to a subroutine. Each thread calls the subroutine and creates its private, local dti. See example in OP [here](https://software.intel.com/en-us/forums/intel-fortran-compiler-for-linux-and-mac-os-x/topic/603148). Infeasible in my case due to too many required variables /too much code.
2. Make dti an allocatable array and allocate with size=number of OMP threads. Don't make dti `!$OMP PRIVATE`, ie., it is shared, and each thread _i_ accesses only dti(_i_). This works but in my case had a pretty adverse performance impact, which I think is due to memory issues (maybe false sharing in CPU cache).
3. `!$OMP THREADPRIVATE(dti)` together with `!$OMP COPYIN(dti)` as suggested in comment 3 of [this post](https://software.intel.com/en-us/forums/intel-visual-fortran-compiler-for-windows/topic/538143). This requires the `SAVE` attribute. Unfortunately, in my case this crashed at runtime, maybe because of a conflict with the `SAVE`. 
4. `!$OMP FIRSTPRIVATE(dti)` and in my case also `!$OMP LASTPRIVATE(dti)`. This didn't seem to work with ifort in the post that @jacobwilliams pointed to, but that is 6 years old. It works for me with Intel compiler 15.x... I may try to confirm that with Intel.

One thing that may be helpful for number 3. or alternatives to 1. would be a constructor. I will open a separate issue for this.

Best, Daniel

**Comment by szaghi** [comment]
@danhar I agree that a *constructor* or a defined assignment could help (in this and other circumstances).

My best regards.

**Comment by jacobwilliams** [comment]
Thanks for looking into it! Very interesting. I was sure that I had used OpenMP before with derived types with allocatable components, but looking back at the code, I see I did the OpenMP loops at a lower level, so there were no types involved.
