### ISSUE TITLE
feature request: constructor

### ISSUE THREAD

**Issue by danhar** [jacobwilliams/bspline-fortran#13]
Here is an example, adapted from [Rouson, Xia, Xu (2014)](http://www.amazon.de/Scientific-Software-Design-Object-Oriented-Way/dp/1107415330/ref=sr_1_1?ie=UTF8&qid=1455891424&sr=8-1&keywords=scientific+software+design+the+object-oriented).

```fortran
module template_class
    type :: t_template
    !...
    end type t_template

    interface t_template
        module procedure constructor
    end interface
contains
    elemental function constructor( ) result (new_instance)
    type(t_template)         :: new_instance
    !...
    end function constructor
end module template_class
```
which allows initialization statements such as
```fortran
dti = t_template
```
which can be useful in cases such as outlined in issue #12 .

**Comment by jacobwilliams** [comment]
Yes, I can do this.

**Comment by szaghi** [comment]
I vote for a constructor, but I do not vote for overloading the derived name. I found that Intel compiler goes (often) on crash when this overloading is done, see [this](https://software.intel.com/en-us/forums/intel-fortran-compiler-for-linux-and-mac-os-x/topic/583935).

**Comment by danhar** [comment]
As you wish. It works with Ifort 15.1.133 and 15.0.090.

**Comment by jacobwilliams** [comment]
I admit, I haven't used much the option to overload the type name.

What I have now is this:
```fortran
type(bspline_3d) :: s
call s%initialize(x,y,z,fcn,kx,ky,kz,iflag)
```
Is that what you mean by "constructor"? @danhar, does this not work for the application in mind? Or does it have to be:
```fortran
type(bspline_3d) :: s
s = bspline_3d(x,y,z,fcn,kx,ky,kz,iflag)
```

**Comment by danhar** [comment]
I must admit that I don't know whether it would solve the problem I had, but one difference is that in the second case, it would just be
```fortran
type(bspline_3d) :: s
s = bspline_3d()
```
I think that, for example after an `!$OMP PRIVATE(s)`, where _s_ is undefined, the statement `s = bspline_3d()` makes it defined, without, for example, allocating the arrays. The `call s%initialize(x,y,z,fcn,kx,ky,kz,iflag)` can follow later.

**Comment by szaghi** [comment]
@jacobwilliams with *constructor* I mean *whatever you want*: a function returning a concrete instance *initialized* or subroutine *initialiazing* a passed argument (that currently is what I prefer).

Currently I like something:
```fortran
type :: foo
  integer, allocatable :: bar(:)
  contains
    procedure, pass(self) :: init
endtype foo
contains 
  subroutine init(self, dims, other)
  class(foo), intent(inout) :: self
  integer, intent(in), optional :: dims
  type(foo), intent(in), optional :: other

  if (present(other) then
    if (allocated(other%foo)) self%bar = other%bar
  else if (present(dims) then
   if (allocated(self%bar)) deallocate(self%bar)
    allocate(self%bar(1:dims))
    self%bar = 0
  endsubroutine 
```


 What I like to point out is that
> if you overload the *consctructor* with the type name, Intel Fortran could have problems.

@danhar I do not understand `It works with Ifort 15.1.133 and 15.0.090.`. With Intel 15.3 (and before) the overloaded constructor could raises the Intel bug as reported in the Intel Forum thread above linked. As FortranFan pointed out (the guy who first point me to found my problem in those days) it seems that until trunk 16.x, Intel Compiler has problems with *constructors* overloading the type name.

My best regards.

**Comment by szaghi** [comment]
> I think that, for example after an `!$OMP PRIVATE(s)`, where s is undefined, the statement `s = bspline_3d()` makes it defined, without, for example, allocating the arrays. The call `s%initialize(x,y,z,fcn,kx,ky,kz,iflag)` can follow later.

The allocation/initialization is not the crucial problem with Intel. Intel has only problems (often, but not always, anyway it is bugged) when the *constructor* name overloads the type name. The approach you like can be obtained safer with

```fortran
s = bspline_3d_constructor()
```
This is the only point that I like to highlight.

**Comment by szaghi** [comment]
In other words

```fortran
  interface t_template
    module procedure constructor
  end interface
```
is not always correctly handled by Intel Fortran 15.x and before. Not sure about 16.x trunk.

**Comment by jacobwilliams** [comment]
Assuming it did work, what about this:

```fortran

    interface bspline_2d
        procedure :: bspline_2d_constructor_empty,&
                     bspline_2d_constructor_auto_knots,&
                     bspline_2d_constructor_specify_knots
    end interface

!*******************************************************************************
    pure elemental function bspline_2d_constructor_empty() result(me)

    implicit none

    type(bspline_2d) :: me

    end function bspline_2d_constructor_empty
!*******************************************************************************
!*******************************************************************************
    function bspline_2d_constructor_auto_knots(x,y,fcn,kx,ky,iflag) result(me)

    implicit none

    type(bspline_2d)                   :: me
    real(wp),dimension(:),intent(in)   :: x
    real(wp),dimension(:),intent(in)   :: y
    real(wp),dimension(:,:),intent(in) :: fcn
    integer,intent(in)                 :: kx
    integer,intent(in)                 :: ky
    integer,intent(out)                :: iflag

    call initialize_2d_auto_knots(me,x,y,fcn,kx,ky,iflag)

    end function bspline_2d_constructor_auto_knots
!*******************************************************************************
!*******************************************************************************
    function bspline_2d_constructor_specify_knots(x,y,fcn,kx,ky,tx,ty,iflag) result(me)

    implicit none

    type(bspline_2d)                   :: me
    real(wp),dimension(:),intent(in)   :: x
    real(wp),dimension(:),intent(in)   :: y
    real(wp),dimension(:,:),intent(in) :: fcn
    integer,intent(in)                 :: kx
    integer,intent(in)                 :: ky
    real(wp),dimension(:),intent(in)   :: tx
    real(wp),dimension(:),intent(in)   :: ty
    integer,intent(out)                :: iflag

    call initialize_2d_specify_knots(me,x,y,fcn,kx,ky,tx,ty,iflag)

    end function bspline_2d_constructor_specify_knots
!*******************************************************************************
```
With the `empty` one not otherwise very useful except for the OpenMP case. The others can be used in place of the `initialize` method if so desired

It seems to compile with Intel 16.1, but haven't tried to run it.

**Comment by danhar** [comment]
That looks good. I must admit that I also don't know to what extent the `empty` case is useful beyond my very particular case, but that's how [Rouson, Xia, Xu (2014)](http://www.amazon.de/Scientific-Software-Design-Object-Oriented-Way/dp/1107415330/ref=sr_1_1?ie=UTF8&qid=1455891424&sr=8-1&keywords=scientific+software+design+the+object-oriented) propose to do it (a very good book for object-oriented design in Fortran). The general idea is that you may want to get access to, e.g., the type-bound procedures before the initialization arguments (`x, y`, etc) become available.

Given that I found a better solution to my OpenMP problem, maybe this feature is not such a high priority. 

Btw, `pure` is redunant in the `empty` case because it is implied by `elemental`.

**Comment by jacobwilliams** [comment]
Done.
