### ISSUE TITLE
pure procedures?

### ISSUE THREAD

**Issue by danhar** [jacobwilliams/bspline-fortran#14]
Would it be a good and feasible idea to make the procedures `pure`? Since the `save` variables are gone, that's one less obstacle. The other obstacle are the error messages. Since an error flag is already present, one could move the messages to a separate (non-pure) type-bound subroutine which takes flag as input and prints the corresponding message.

In my case, the spline evaluation appears in a bottleneck part of the code that could benefit from optimization which the compiler can do for `pure` procedures, and bspline is the only element preventing this.

**Comment by szaghi** [comment]
:+1:

**Comment by jacobwilliams** [comment]
It's a good idea. I can do it.

**Comment by jacobwilliams** [comment]
Well, I've hit a snag with the `initialize` subroutines. They now look something like this:
```fortran
    pure subroutine initialize_1d_auto_knots(me,x,fcn,kx,iflag)

    implicit none

    class(bspline_1d),intent(out)    :: me
    real(wp),dimension(:),intent(in) :: x
    real(wp),dimension(:),intent(in) :: fcn
    integer,intent(in)               :: kx
    integer,intent(out)              :: iflag
...
```
However, it doesn't compile because:
```
Error: INTENT(OUT) argument 'me' of pure procedure ‘initialize_1d_auto_knots’ at (1) may not be polymorphic
```
Maybe these would have to be eliminated in favor of the function constructors?

**Comment by szaghi** [comment]
Not sure, but `me` is the passed argument right? What if you declare it `intent(inout)`? 

If you use a function constructor the `me` becomes the *result* and it should be not polymorphic or it should be an allocatable class, I guess (not sure again).

**Comment by jacobwilliams** [comment]
I can change it to `inout` but then I'd loose the automatic deallocation of the variables inside which needs to be done (in case you are reusing the type after having previously initialized it with different data). Maybe I can get it to work if I do something like this:

```fortran
    pure subroutine initialize_1d_auto_knots(me,x,fcn,kx,iflag)

    implicit none

    class(bspline_1d),intent(inout)  :: me
    real(wp),dimension(:),intent(in) :: x
    real(wp),dimension(:),intent(in) :: fcn
    integer,intent(in)               :: kx
    integer,intent(out)              :: iflag

    select type (me)
    type is (bspline_1d)
        call destroy_bspline_1d(me)
    end select
...
```
Where `destroy_bspline_1d` has a dummy argument `type(bspline_1d),intent(out)`. That seems super clunky though. Note that the normal `destroy` method in the `bspline_1d` type can't be pure for the same error above.

**Comment by szaghi** [comment]
@jacobwilliams yes, I agree that the code becomes verbose, but, due to my paranoic soul, I like more the explicit *free* than the automatic: my practice is that for all type having allocatable members provide (and use) a `free` method and a corresponding `final procedure` (that by convention I name `finalize`). Thus also in the `bspline%destroy` I like to declare it `pure` (or if possible `elemental`) with `intent(inout)` of passed argument. If `bspline` has derived type members then I will explicitely call their `destroy` methods... yes I am counscious that this approach is boring and verbose, but I prefer the *explict and under-control* way.

This is only my way, feel free to put it into the recicle-bin, but if you want to enable purity some compromises are necessary.

See you soon.

**Comment by danhar** [comment]
Could you try to declare a `type` instead of a `class`, i.e., 
```fortran
type(bspline_1d),intent(out)    :: me
```
instead of
```fortran
class(bspline_1d),intent(out)    :: me
```
I remember that in my constructor example in #13 `class` would not work and `type` was required. I don't remember why, but if I'd had to make a random(!) guess, I'd say that because of the `intent(out)` the procedure needs to know the concrete `type` it needs to return. Your suggested verbose workaround
```fortran
select type (me)
    type is (bspline_1d)
        call destroy_bspline_1d(me)
end select
```
seems to do something along those lines, selecting by `type` where only one type is possible. The same may be true for the destroy method.

**Comment by danhar** [comment]
PS: the `pure` may have enforced that the `type` be specified inside the procedure and not somewhere else.

**Comment by szaghi** [comment]
@danhar 
If you declare a `type(bspline)` you will not have a TBP constructor, but an *external* constructor.  This is legitimate and feasible, but it is not much an OOP approach rather a functional one. On the contrary, simply declaring it `intent(inout)` there will no need for type-guards:

```fortran
type :: bspline 
  real, allocatable :: foo(:)
  contains
    procedure, pass(me) :: init
    procedure, pass(me) :: free
    final                            :: finalize
endtype bspline
contains
pure subroutine init(me, ...)
    class(bspline), intent(inout)  :: me
    ...
   call me%free
   ! your initialize stuff: no type-guards are needed 
end subroutine init

pure subroutine free(me)
    class(bspline), intent(inout)  :: me
    if (allocated(me%foo)) deallocate(me%foo)
end subroutine free

pure subroutine finalize(me)
    type(bspline), intent(inout)  :: me
    call me%free
end subroutine finalize
```

Cheers

**Comment by danhar** [comment]
@szaghi : both of your comments were very interesting to me, thanks!

**Comment by jacobwilliams** [comment]
@szaghi Your approach is basically how I always used to do things (explicitly deallocating everything in the `free` routine). Lately, though, I've started to trust that the compilers will automatically deallocate everything if the argument is `intent(out)`. I think there's some subtle reason the standard doesn't allow this when combining pure with polymorphism (something to do with potential non-pure finalizers?) I'll thinker with it some more.

**Comment by szaghi** [comment]
@jacobwilliams 
> I think there's some subtle reason the standard doesn't allow this when combining pure with polymorphism (something to do with potential non-pure finalizers?)

I agree.

>  I'll thinker with it some more.

Please, take my comments only as they are... comments of *not so smart* programmer! 

See you soon.

**Comment by jacobwilliams** [comment]
Your comments are always welcome (and helpful).

I've got an implementation of everything on #17. Will test some more. With Gfortran, the 1D speed test does seem to be faster, but oddly enough, all the other dimensions are slower! Intel might behave better...I'll test that later.

**Comment by jacobwilliams** [comment]
Committed to master. Will be in 5.0 release.

**Comment by danhar** [comment]
Absolutely great! Amazing how responsive and quick you are!
