### ISSUE TITLE
changes to initialization routines arguments

### ISSUE THREAD

**Issue by jacobwilliams** [jacobwilliams/bspline-fortran#16]
I'm considering redefining the `iflag` return values from the initialization routines so that a `0` value means no errors. This would match the evaluation routines. Also, for specifying the knots, there should be a logical input `specify_knots`, rather than the current dual-use `iflag` variable (which is an artifact from the original code). This would break backward compatibility, so it would be in the 5.0 release.

**Comment by danhar** [comment]
Sounds good. The `specify_knots` would only break compatibility of the subroutine interfaces, not the OO interfaces, right?

**Comment by jacobwilliams** [comment]
Correct. With the exception of the meaning of `iflag` for the initialization routines (`0` now means success, whereas formerly `1` meant success). `1` now means "class is not initialized" (which had no error code before).

**Comment by jacobwilliams** [comment]
Committed to master. Will be in 5.0 release.
