### ISSUE TITLE
check length of inputs?

### ISSUE THREAD

**Issue by danhar** [jacobwilliams/bspline-fortran#19]
I think `db[X]ink` doesn't check whether the abscissae `x` (, `y`,…) and the function values `fcn` have the same length. Should it? If so, should it return an appropriate flag (or issue a warning)?

**Comment by jacobwilliams** [comment]
You mean check that `size(f,1)==size(x)`, `size(f,2)==size(y)`, etc.? No, I don't think I have that check. Yes, I probably should add it. I'll do it after the merge of the `pure` branch, which should mostly be done. Just wanted to do some more tests.

**Comment by danhar** [comment]
yes, that's what I mean. I actually had a bug in my code because I didn't respect this and the code ran fine.

**Comment by jacobwilliams** [comment]
Committed to master. Will be in 5.0 release.

**Comment by danhar** [comment]
Thanks! You are fantastic!
