### ISSUE TITLE
Wsurprising?

### ISSUE THREAD

**Issue by gabrielgggg** [jacobwilliams/bspline-fortran#27]
Hello! When compiling with gfortran with -Wall, every type definition gives this warning:

     mpif90 -Ofast -march=native -mtune=native -pipe -g -fopenmp -Wall -c src/bspline_oo_module.f90 src/bspline_oo_module.f90:62:52:

     type,extends(bspline_class),public :: bspline_1d
                                                    1
     Warning: Only array FINAL procedures declared for derived type ‘bspline_1d’ defined at (1), suggest also scalar one [-Wsurprising]

Can it be safely ignored? Thank you!

**Comment by jacobwilliams** [comment]
I believe this was a gfortran bug (what version are you using?). I think it was fixed in a recent release. It can be ignored in any case.

**Comment by gabrielgggg** [comment]
Thank you for the quick reply and all your work on this library! I'm using

    GNU Fortran (Ubuntu 6.3.0-12ubuntu2) 6.3.0 20170406
    Copyright (C) 2016 Free Software Foundation, Inc.

**Comment by jacobwilliams** [comment]
See [Bug 58175 - [OOP] Incorrect warning message on scalar finalizer](https://gcc.gnu.org/bugzilla/show_bug.cgi?id=58175). I'm using gfortran 7.1.0 and I don't get those warnings. I think you can just ignore them (or upgrade).
