### ISSUE TITLE
1D bspline

### ISSUE THREAD

**Issue by danhar** [jacobwilliams/bspline-fortran#3]
it would be great to have also bsplines for 1D interpolation with the same call syntax, i.e.,

db1ink(x,nx,fcn,kx,tx,bcoef,iflag)
db1val(...)

Or is there something that I am missing?

**Comment by jacobwilliams** [comment]
Great idea. It's not currently there, but could be easily added.

**Comment by danhar** [comment]
l would like to implement it myself and contribute to the project, but sadly I am just a dumb economist who fails even to figure out the details of db2val, e.g., what dintrv is for and how to adapt it to the 1D case... Is there any chance that this will be added in the near future, so I could use it in current work? I already use your bsplines for higher dimensions, but need to cover the 'degenerate' 1D case as well.

And thanks so much for this fantastic code!

**Comment by jacobwilliams** [comment]
I'll try to take a look at it tonight or tomorrow. I think it will be pretty easy to add.

**Comment by jacobwilliams** [comment]
Done in 3.3.0. Let me know if it works.

**Comment by danhar** [comment]
Amazing! I'll try it out it this week. Thanks so much!
