### ISSUE TITLE
Thread safety/bounds check failures

### ISSUE THREAD

**Issue by pbregener** [jacobwilliams/bspline-fortran#35]
There appear to be problems related to the thread safety of this library.

Below code works fine when running without OpenMP:
```fortran
program main
use bspline_module
use bspline_kinds_module

implicit none
type(bspline_1d) :: s
real(kind=wp), dimension(:), allocatable :: x, fcn
real(kind=wp) :: q, f
integer :: i, iflag
integer, parameter :: size = 30
print *, '*** START'

print *, '*** INIT'
allocate(x(size), fcn(size))

do i = 1, size
     x(i) = real(i, wp)
     fcn(i) = x(i)**2
     print *, i, x(i), fcn(i)
end do

call s%initialize(x, fcn, 4, iflag)
print *, iflag

print *, '*** EVAL'

!$omp parallel do default(shared) private(i, q, f, iflag)
do i = 1, 50000
     call random_number(q)
     q = 1.0_wp + q * real(size-1, wp)
     call s%evaluate(q, 0, f, iflag)
     if (iflag /= 0) print *, q, iflag, s%status_message(iflag)
end do
!$omp end parallel do

print *, '*** END'

end program main

```

Enabling bounds checks and enabling OpenMP then gives out-of-bounds errors when evaluating the spline in parallel. Both `gfortran` (with `-fcheck=bounds`) and `ifort` (with `-check bounds`) throw these errors and I doubt that they are false positives.

`ifort` output:
```
forrtl: severe (408): fort: (3): Subscript #1 of the array A has value 0 which is less than the lower bound of 1
```

`gfortran` output:
```
At line 3056 of file [...]/bspline_sub_module.f90
Fortran runtime error: Index '0' of dimension 1 of array 'a' below lower bound of 1
```

Have you come across this before @jacobwilliams or I am making some mistake here?

**Comment by pbregener** [comment]
Modifying the declaration of `s` slightly in above example
```fortran
type(bspline_1d), save :: s
!$omp threadprivate(s)
```
and adding a `copyin(s)` clause to the `omp parallel do` section works as a workaround.

IMHO this indicates thread safety problems in at least the OO part of this library.

**Comment by jacobwilliams** [comment]
There was a ticket about this before (see #12). I think the conclusion was that OpenMP doesn't work well with "modern" OO features. I don't know if there's anything we can do to fix it? The function interface should work fine.

**Comment by pbregener** [comment]
Oh, sorry, I wasn't aware of that issue. I will have another look at both that ticket and the general situation.

But isn't the README a bit misleading then? It says that both the subroutine and the OO interface are thread safe.

**Comment by pbregener** [comment]
Oh, sorry, I wasn't aware of that issue. I will have another look at both that ticket and the general situation.

But isn't the README a bit misleading then? It says that both the subroutine and the OO interface are thread safe.

**Comment by pbregener** [comment]
Will close this in favor of #12 now, even though that issue is currently closed, too.
