### ISSUE TITLE
Use of bspline-fortran

### ISSUE THREAD

**Issue by Naaba** [jacobwilliams/bspline-fortran#37]
Hi,
We used your library to develop our project and we would like to pusblish it on github with a GPL license.
Is that compatible with you? 
Best regards,
Benjamin

**Comment by jacobwilliams** [comment]
Sure, you can include it with GPL software, but note that the bspline-fortran code is not GPL. You have to include the original bspline-fortran [license file](https://github.com/jacobwilliams/bspline-fortran/blob/master/LICENSE) in any redistribution of the source or binaries.

I'd be interested in seeing what you used it for. Glad to know that it's being useful.

**Comment by Naaba** [comment]
Hi Jacob, I hope I included it correctly. 
here is the project https://github.com/LHEEA/Grid2Grid 
bspline-fortran is used to interpolate a solution of a numerical solution from a coarse grid to a finer one
