### ISSUE TITLE
API documentation broken

### ISSUE THREAD

**Issue by Exteris** [jacobwilliams/bspline-fortran#38]
Hi Jacob,

Thanks for this excellent library.
I noticed that the documentation on jacobwilliams.github.io is broken for this package, perhaps something went wrong on github pages? Could you take a look?

Thanks,
Daan

http://jacobwilliams.github.io/bspline-fortran/

**Comment by jacobwilliams** [comment]
I gave up trying to get Travis-Ci to use the latest master ford. We'll just have to wait until @cmacmackin publishes a new release on pypi. 😄

Meanwhile, I just reverted it back to the last one that worked.

**Comment by jacobwilliams** [comment]
Fixed by reverting to markdown to 2.6.9 in the Travis-CI file. That one works with the ford on pypi.
