### ISSUE TITLE
Problem in parallelized environment

### ISSUE THREAD

**Issue by danhar** [jacobwilliams/bspline-fortran#4]
The code can't be used in a parallelized environment, because there are variables with the SAVE attribute in the subroutines db[X]val. This makes them effectively global, so that different parallel threads -each calling db[X]val independently- will overwrite the value, resulting in run-time errors. I think this behaviour will also occur for the object-oriented version (not tested), but it may be easier to remedy there.

In my opinion, modern Fortran code should be written so that it can be used in parallel applications. For example, in my case, an outer loop is parallelized with OpenMP, and within the loop each thread uses bspline-fortran for interpolation. I think this is a common setting, and that bspline-fortran should be a prime candidate for such high-performance applications.

For parallelization with OpenMP, I have implemented an easy solution (easy to implement, though it took me a complete day to figure out what was going wrong...). For example for subroutine db2val, replace the lines 

    integer,save :: inbvx = 1
    integer,save :: iloy  = 1

by

    integer,save :: inbvx
    integer,save :: iloy
    !$OMP THREADPRIVATE(inbvx, iloy)
    inbvx = 1
    iloy  = 1

This creates separate SAVEd variables inbvx, iloy for each thread, which are then 'global' within the thread. In my own application, this resolved the problems. Compiling and running with the Intel Fortran Compiler with maximum debug flags didn't report any warnings or errors. However, I am not a programmer by training, so I can't say how good or reliable or general the solution is.

For the object-oriented version, one could make use of the private type components that correspond to inbvx, iloy to avoid the need for the SAVE attribute. This would have the advantage of being more portable, since it wouldn't be limited to OpenMP. But it would require a little bit larger modifications of db[X]val and maybe the routines called by it, I believe. This object-oriented solution and the OpenMP-based one are not mutually exclusive.

**Comment by jacobwilliams** [comment]
Yes, I was aware of this. The original code included those `save` variables and was not thread safe. These variables are used to reduce the overhead of searching for the location of the independent variables in the knot sequence, by saving the indices of the last call.

My preferred solution would actually be to get rid of the subroutine interface, and require you to use the object-oriented interface. Then these variables live in the classes, and there is no need for the saved variables (which are only used now for the subroutine interface).  What do you think?

Also:

**Comment by jacobwilliams** [comment]
See f351c85 for a solution. I just made these variables non-optional, which should make them all thread-safe. You just have to initialize the values to 1 before you call it. I'll test it some more and merge it into the master branch (it does break backward compatibility, so it will be release 4.0).

**Comment by danhar** [comment]
I had a pretty thorough look, but -again- I am just a user and don't understand some details. As much as I like object-oriented-Fortran and program nearly everything along the OO paradigm, I would not require the use of the OO interface, because many (legacy) interpolation routines have an interface similar to the bspline-subroutines, which makes it easy to switch. For example, in my case, a user-supplied parameter determines whether to use bsplines or orthogonal polynomials, which -broadly speaking- then have a very similar call structure.

As you note, the inout for the indeces (in conjunction with the inout for 'me') also fixes the OO interpolation, which previously always over-wrote the SAVEd variables. 

While the subroutine calls now get chunkier with all the arguments, I can't think of a better solution. I will test it in my application, though it might take a while before I get to it (you shouldn't wait for that with the 4.0 release).

**Comment by jacobwilliams** [comment]
Agreed. I kept them both (you just have to deal with the extra arguments for the subroutine interface, which isn't a big deal in the grand scheme of things). You can reopen this ticket if you have any problems (or open a new one).

**Comment by danhar** [comment]
I am finally taking a look at the new release. I would update the History of db[x]val with a new entry, also indicating that it breaks backward compatibility.
