### ISSUE TITLE
Citation

### ISSUE THREAD

**Issue by YoungmChoi** [jacobwilliams/bspline-fortran#48]
Dear Williams,

Could you upload your open source codes into open source software journal like: 

The Journal of Open Source Software, ArXiv, ...

for easy citation?:)

Best Regards,
Young-Myung Choi

**Comment by jacobwilliams** [comment]
[![DOI](https://zenodo.org/badge/31299552.svg)](https://zenodo.org/badge/latestdoi/31299552)
