### ISSUE TITLE
bad use of stack memory instead of heap

### ISSUE THREAD

**Issue by hennink** [jacobwilliams/bspline-fortran#50]
I'm afraid that many routines currently use a wrong type of array in Fortran. This leads to a much lower data size limit than could otherwise be achieved. 

All large local variables should allocatable, because they use heap memory by default. Currently many large local arrays are of automatic size, so they get allocated on the stack. [This commit](https://github.com/hennink/bspline-fortran/commit/62504342d9bec3a7a71cebdb5d5e960b976d4255) shows how to correct the `db3ink` procedure. The fix is straightforward, but a little tedious to implement everywhere.

I see two solutions:

1. The 'right' approach: do what I did for `db3ink` in all procedures, and then merge the branch.

1. A hack: use a compiler option to force all arrays onto the heap. [This commit](https://github.com/hennink/bspline-fortran/commit/29d1f0e58451989abc1091567a23587afcea53c2) shows how I did this with the intel compiler. I don't know how to do the equivalent for the GNU compiler.

---

For reference, these were the limits for the data sizes for
```fortran
    type(bspline_3d) :: spline
    ...
    call spline%initialize(  &
          x=xi, y=yi, z=zi,  &
          fcn=data,  &
          kx=4, ky=4, kz=4,  &
          iflag=iflag,  &
          extrap=.true.  &
      )
```
on my computer cluster:

* original maximum: `size(xi) * size(yi) * size(zi) = 9 * 9 * 9` ;

* after fixing `db3ink`:  `9 * 9 * 20` (approximate);

* after compiling everything with `-heap-arrays`:  `264 * 240 * 240` still works. Did not test larger array.

**Comment by jacobwilliams** [comment]
Ah yes, I have definitely encountered this issue before in other codes.

The funny thing is, in the original Fortran 77 code, these work arrays were inputs to the subroutines I think. I think my preference might be to restore that behavior. That way, the large arrays don't have to be reallocated every time the routine is called. They could be added to the object-oriented interface inside the various classes, so the user doesn't even have to worry about them.

I'm curious to know if you noticed any speed degradation? The stack is faster than the heap right?

**Comment by hennink** [comment]
No, I did not test the performance.

_[Side note: I suspect that strictly speaking the Fortran standard is silent on which type of memory to use for an array, but in practice automatic arrays are put on the stack.]_

Reasons against passing `temp` and `work` arrays as a dummies:

1. It's confusing to read.

1. It sound like much more work than making the arrays allocatable.

1. I'd be very surprised if the current code is noticeably slower in any practical example.

    I'm pretty sure the Intel compilers expect you to use allocatables, and optimize for that, though I can't remember where I read an Intel developer state this. Furthermore, repeated allocation and deallocation of large arrays is not necessarily slow with a decent optimizer.

1. My limited understanding is that spline initialization is rarely a significant part of any program that is big enough to warrant optimization.

But this decision is really up to you.

**Comment by jacobwilliams** [comment]
I was thinking more for the `db*val` routines (which may be called millions of times, even though the `db*ink` routine might only be called once).

I've got some tests going on the `50-work-arrays` branch. I will test some more. The `stack_size_test_oo.f90` test keeps increasing the data size until it crashes. I've got it to go up to `270 x 270 x 270` on my laptop before I killed it.

Note that the object-oriented interface didn't change, so users of that wouldn't have to make any changes to their code.

**Comment by jacobwilliams** [comment]
Note: I'm also seeing this line crash for large sizes:
```fortran
temp = reshape( fcn, [nx*ny*nz] )
```
with intel, but not with gfortran. I may need to replace this with loops.

**Comment by hennink** [comment]
This seems directly related to the example in [Intel's docs](https://software.intel.com/en-us/fortran-compiler-developer-guide-and-reference-heap-arrays) for the `-heap-arrays` option.

It's probably considered a feature that the Fortran standard tells you nothing about the type of memory that is used (it's meant to be a fairly high-level language), but then you do get different behavior for different compilers.

Yes, you could write your own `reshape` function with an allocatable result.

If you don't need an actual copy of the data, and `fcn` is contiguous, then you can make `fcn` a target and use a bounds-remapping pointer: `temp(1:nx*ny*nz) => fcn`.

**Comment by hennink** [comment]
I tested this, and my code runs now without compiling with the `heap-arrays` flag.

Many thanks for the fast and thorough response.
