### ISSUE TITLE
Is it possible to use bspline-fortran to perform linear interpolation

### ISSUE THREAD

**Issue by Gjacquenot** [jacobwilliams/bspline-fortran#88]
I would like to run elementary check on my usage of this library.

And I wonder if it can be used to perform linear interpolation.

Setting order parameter `k` to 1 achieves this?

If so, it would be nice to mention it in documentation !

**Comment by jacobwilliams** [comment]
I think `k=2` would be linear. Or at least that would mean a 1st degree spline. But is that the same as linear interpolation? I've never tried it.

If you want linear interpolation, I would use this library: https://github.com/jacobwilliams/finterp

**Comment by jacobwilliams** [comment]
![image](https://github.com/jacobwilliams/bspline-fortran/assets/6483379/e58c992b-f549-431e-84f6-07db313630c4)

It seems that it mostly is, but for some reason the region near the right bound isn't right. I need to look into why this is...

**Comment by jacobwilliams** [comment]
OK, never mind. I had a bug in my code. It looks like it's all fine. 

So, yes `k=2` is l linear interpolation.

**Comment by Gjacquenot** [comment]
Thank you for the time you took to investigate this!
